# Generated by Django 4.0.6 on 2022-09-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_alter_detail_ram_alter_detail_adapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='RAM',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
