# Generated by Django 4.0.6 on 2022-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_remove_brand_category_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.TextField(blank=True),
        ),
    ]
