# Generated by Django 4.0.6 on 2022-09-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_brand_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='RAM',
            field=models.CharField(blank=True, max_length=100, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='adapter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sạc'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='battery',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='chip',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chip'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='front_camera',
            field=models.CharField(blank=True, max_length=100, verbose_name='Camera trước'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='memory',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bộ nhớ trong'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hệ điều hành'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='rear_camera',
            field=models.CharField(blank=True, max_length=100, verbose_name='Camera sau'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='screen',
            field=models.CharField(blank=True, max_length=100, verbose_name='Màn hình'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sim',
            field=models.CharField(blank=True, max_length=200, verbose_name='SIM'),
        ),
    ]
