# Generated by Django 4.0.6 on 2022-09-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0012_alter_detail_ram_alter_detail_adapter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="RAM",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="adapter",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="detail",
            name="battery",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="detail",
            name="chip",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="detail",
            name="front_camera",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="memory",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="detail",
            name="operating_system",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="rear_camera",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="screen",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="detail",
            name="sim",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(
                fields=[
                    "screen",
                    "operating_system",
                    "rear_camera",
                    "front_camera",
                    "chip",
                    "RAM",
                    "memory",
                    "sim",
                    "battery",
                    "adapter",
                ],
                name="Detail_screen_fe1d66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["screen"], name="Màn hình"),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["operating_system"], name="Hệ điều hành"),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["rear_camera"], name="Camera sau"),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["front_camera"], name="Camera trước"),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["chip"], name="Chip"),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["RAM"], name="RAM"),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["memory"], name="Bộ nhớ trong"),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["sim"], name="SIM"),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["battery"], name="Dung lượng pin"),
        ),
        migrations.AddIndex(
            model_name="detail",
            index=models.Index(fields=["adapter"], name="Sạc"),
        ),
    ]
