# Generated by Django 4.0.6 on 2022-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_alter_detail_ram_alter_detail_adapter_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='detail',
            name='Detail_screen_fe1d66_idx',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='Màn hình',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='Hệ điều hành',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='Camera sau',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='Camera trước',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='Chip',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='RAM',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='Bộ nhớ trong',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='SIM',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='Dung lượng pin',
        ),
        migrations.RemoveIndex(
            model_name='detail',
            name='Sạc',
        ),
        migrations.AlterField(
            model_name='detail',
            name='RAM',
            field=models.CharField(blank=True, max_length=100, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='adapter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sạc'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='battery',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='chip',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chip'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='front_camera',
            field=models.CharField(blank=True, max_length=100, verbose_name='Camera trước'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='memory',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bộ nhớ trong'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hệ điều hành'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='rear_camera',
            field=models.CharField(blank=True, max_length=100, verbose_name='Camera sau'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='screen',
            field=models.CharField(blank=True, max_length=100, verbose_name='Màn hình'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sim',
            field=models.CharField(blank=True, max_length=200, verbose_name='SIM'),
        ),
    ]
