# Generated by Django 4.0.6 on 2022-09-10 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_remove_detail_detail_screen_fe1d66_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
