# Generated by Django 5.2 on 2025-04-26 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0022_remove_profile_phone_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Chưa thanh toán'), (1, 'Đã thanh toán'), (2, 'Đang giao hàng'), (3, 'Giao hàng thành công')], default=0),
        ),
    ]
